/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'StateAuditJob': CronHandler<never>
    'ProcessFoodOrder': EventHandler<{ id: number; name: string; photoUrl: string; foodOrder?: { id: string; quantity: number }; email: string }, { topic: 'ts.order.processed'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'Notification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: { name: string; photoUrl: string }; foodOrder?: { id: string; quantity: number } }, ApiResponse<200, { id: number; name: string; photoUrl: string; status?: 'available' | 'pending' | 'sold'; createdAt?: string }>, { topic: 'ts.pet.created'; data: { id: number; name: string; photoUrl: string; foodOrder?: { id: string; quantity: number }; email: string } }>
  }
}