/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: number; petId: number }, { topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'Notification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: { name: string; photoUrl: string }; foodOrder?: { id: string; quantity: number } }, ApiResponse<200, { id: number; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: number; petId: number } }>
    'GmailAuthInit': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { authUrl: string; message: string }> | ApiResponse<500, { error: string }>, never>
    'GmailAuthCallback': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { token: string; user: { id: string; email: string; name: string; picture?: string }; message: string }> | ApiResponse<400, { error: string }> | ApiResponse<500, { error: string }>, never>
    'VerifyGmailToken': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { user: { userId: string; email: string; name: string; picture?: string }; valid: boolean }> | ApiResponse<401, { error: string; valid: boolean }> | ApiResponse<500, { error: string }>, never>
  }
}