"""Add use_ai_outfill to job table

Revision ID: a6a98baf515f
Revises: 0b368412be44
Create Date: 2025-09-14 17:41:34.956351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a98baf515f'
down_revision: Union[str, Sequence[str], None] = '0b368412be44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('use_ai_outfill', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('outfill_strength', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'outfill_strength')
    op.drop_column('jobs', 'use_ai_outfill')
    # ### end Alembic commands ###
